### PR TITLE
ftests: Update test 45 to match the pybindings

### PR DESCRIPTION
**Pull request by drakenclimber**
Signed-off-by: Tom Hromatka <tom.hromatka@oracle.com>

### CODE REVIEW

**Comment by drakenclimber** [comment]
Here's a passing test run:
https://github.com/drakenclimber/libcgroup/actions/runs/2209313460

**Comment by kamalesh-babulal** [comment]
@drakenclimber Thanks for the patch, the rename to `mount_points` looks good.
While trying to test the patch, it fails with 50014 (cgroup not initialized):
```
sudo ./ftests.py -N 45 -l 10 -L foo --no-container
-----------------------------------------------------------------
Test Results:
        Run Date:                          Apr 24 05:50:25
        Passed:                                  0 test(s)
        Skipped:                                 0 test(s)
        Failed:                                  1 test(s)
                Test:                           045-pybindings-list_mount_points.py - cgroup_list_mount_points failed: 50014
-----------------------------------------------------------------
[snip]
```
I guess the reason for the test cases failure is that  the `cgroup_list_mount_points()`
expects the `cgroup_init()` to be called ahead so that the `cg_mount_table[] ` is
populated and directly calling `mount_points` return 50014.  Empty initialization like:
```
@@ -36,6 +38,7 @@ def test(config):
     result = consts.TEST_PASSED
     cause = None
 
+    Cgroup(CGNAME, Version.CGROUP_V1)
     mount_points_v1 = Cgroup.mount_points(Version.CGROUP_V1)
     mount_points_v2 = Cgroup.mount_points(Version.CGROUP_V2)
     if not mount_points_v1 and not mount_points_v2:
```
helps in the test case passing.

**Comment by drakenclimber** [comment]
Thanks for the comment, @kamalesh-babulal.  It's fixed in this commit https://github.com/libcgroup/libcgroup/pull/135/commits/302de2eeb8eecd65a031a851d3df7d0e153c94b0.  Tests passed as well, but code coverage numbers went way down.  Don't know what's up with that.

**Comment by drakenclimber** [comment]
Pushed to main in commit 849f272e5785

**Pull request closed without merging**
