### PR TITLE
Make the automated tests more resilient

### PR DESCRIPTION
**Pull request by drakenclimber**

### CODE REVIEW

**Comment by drakenclimber** [comment]
This pull request has now run successfully five times in a row against the v1, v1/v2, and v2 functional tests! :)

**Review by kamalesh-babulal — APPROVED** [review]

**Comment by kamalesh-babulal** [comment]
@drakenclimber Thanks for fixing the GitHub actions issues, I am excited :) Hope you noticed the `LGTM` complaining about using `'BaseException`.

**Comment by drakenclimber** [comment]
This pull request has now run successfully five times in a row against the v1, v1/v2, and v2 functional tests! :)

> @drakenclimber Thanks for fixing the GitHub actions issues, I am excited :) Hope you noticed the `LGTM` complaining about using `'BaseException`.

Yep.  I fixed it in the last forced push.

**Comment by drakenclimber** [comment]
Pushed to main.  Thanks, all.

**Pull request closed without merging**
